### ISSUE TITLE
Filled Button Style before iOS 15.0 ⚠️ 

### ISSUE THREAD

**Issue by ahmdyasser** [motoon-eg/dokan-store#82]
In `VerificationViewController.xib`, set button style to 'default'  since other styles is only availabe in iOS 15.0 and above

![image](https://user-images.githubusercontent.com/42544598/181823016-84abbfb8-81e9-4984-8a06-716990dc5336.png)

![image](https://user-images.githubusercontent.com/42544598/181823068-5a6079d1-6795-41e4-97ca-81f239d9288b.png)

**Comment by RaniaZeid** [comment]
i already solved it and create pull request feat/updateverificationscene but I think it removed

**Comment by ahmdyasser** [comment]
@RaniaZeid  can you link that PR?
